### ISSUE TITLE
Missing event data for "A Little Help From My Friend"

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#2432]
## Description

The quest errors because of missing event data

## Wowhead link

https://classic.wowhead.com/quest=4491/a-little-help-from-my-friends

## Screenshots

<img width="997" alt="grafik" src="https://user-images.githubusercontent.com/33514570/97561767-f04ed900-19e0-11eb-8cd0-860f20f3f4b5.png">

## Questie version

v6.1.0

**Comment by drejjmit** [comment]
We have this in English correction. Will it not use that only trigger end x/y for all languages?

[4491] = { 
[questKeys.triggerEnd] = {"Escort Ringo to Spraggle Frock at Marshal's Refuge", {[zoneIDs.UN_GORO_CRATER]={{43.71,8.29},},},},
},

**Comment by BreakBB** [comment]
Hmmm that should work 🤔 And the commit is quite old as well. So it seems there is something wrong. Could also be related to the way we currently match objectives (which I am refactoring).

**Comment by BreakBB** [comment]
Will most likely also been fixed with #2438

**Comment by BreakBB** [comment]
Should be fixed by #2438

**Comment by Eahlstan** [comment]
This is still an issue.

![Image](https://github.com/user-attachments/assets/b08609fa-44a6-4202-8dfa-5e7fbf11acd8)

**Comment by Cabro** [comment]
~~Can you run this command `/dump C_QuestLog.GetQuestObjectives(4492)`?~~

What game flavor are you playing on and what Questie version do you have? @Eahlstan

**Comment by Eahlstan** [comment]
Well, sadly I just died. So I'm not able to do this until I leveled up again.

Was Classic Anniversary Hardcore, newest Questie 10.23.0.

**Comment by Cabro** [comment]
You should be able to run it from any char. From what i see quest 4492 shouldn't have any objective, so i am very confused why you're getting that objective mismatch error

**Comment by Eahlstan** [comment]
```
[1]={
    [1]={
        type="event",
        numRequired=1,
        finished=false,
        text="Ringo zu Spraggle Frock in Marshals Zuflucht begleiten",
        numFulfilled=0
    }
}
```

**Comment by Cabro** [comment]
This is for 4492, yes?

**Comment by Eahlstan** [comment]
Yes.

**Comment by Cabro** [comment]
This is super confusing, can you run the command again, for both 4491 and 4492 and write here or better, make a snippet of your screen with the results? I think you gave me the results of the dump from 4491 earlier

**Comment by Eahlstan** [comment]
Looks like there is no 4491?

![Image](https://github.com/user-attachments/assets/0cd8c4ed-67e8-4a8e-b7aa-ee41ab45b4fd)

**Comment by Cabro** [comment]
There is 4491 too, you need to run it again, the first time it was to cache the quest. BUT i am ... seriously confused now, because our DB, wowhead's DB and every other DB has them with 4492 "go to ringo" and 4491 "escort ringo back to the refuge". Hardcore seems to have them switched... This is pain

**Comment by Eahlstan** [comment]
> There is 4491 too, you need to run it again, the first time it was to cache the quest. BUT i am ... seriously confused now, because our DB, wowhead's DB and every other DB has them with 4492 "go to ringo" and 4491 "escort ringo back to the refuge". Hardcore seems to have them switched... This is pain

It's not hardcore related, my dead character transferred to the non-hardcore realm looks like this:

![Image](https://github.com/user-attachments/assets/c0e6fb29-cde8-419a-a96f-786c6480a48a)

Season looks like this:

![Image](https://github.com/user-attachments/assets/7930d781-d452-4ad8-8ccb-cab8ee604315)

**Comment by Cabro** [comment]
![Image](https://github.com/user-attachments/assets/e27c85e1-b825-48f4-a858-de58ad24b845)

This is what i get on Hardcore. enUS client.

I believe this is blizzard spaghetti with switching quests for deDE clients. Most likely their intern switched these 2. Can you try on an enUS client and see if you still get the error?

**Comment by Eahlstan** [comment]
This just going to confuse you more. I changed everything I could find to English, let it download and update and now it looks like this:

![Image](https://github.com/user-attachments/assets/fc835b89-0426-4e0f-8864-d84fd77543e6)

On my dead char though:

![Image](https://github.com/user-attachments/assets/aca13938-c332-4601-a637-eba578e8c2f2)

**Comment by Cabro** [comment]
Yeah, this is 100% blizzard locale fuckup.
This is what we have in our DB, wowhead has in their DB etc

I assume you're getting no error now?

**Comment by Eahlstan** [comment]
> I assume you're getting no error now?

Not on the dead character, no.

**Comment by Cabro** [comment]
Absolutely insane.

**Comment by Cabro** [comment]
I pushed "something" to attempt to fix it for deDE next time you get there. Do come here and let us know if it worked or not, please!

**Comment by Eahlstan** [comment]
I copied the file you modified, it now looks like this in game:

![Image](https://github.com/user-attachments/assets/e3f8b433-3160-4bcd-92ba-920a3076f030)

Thanks for your fix.

**Comment by Cabro** [comment]
So no more error now on deDE?

**Comment by Eahlstan** [comment]
No, looks fine.
