### ISSUE TITLE
Ror Hide Brutes - faction display error

### ISSUE THREAD

**Issue by Nerillida** [Questie/Questie#2756]
version 6.3.10 and 6.3.11
Map showing 
https://tbc.wowhead.com/npc=1939/rot-hide-brute
They drop (among others)
https://tbc.wowhead.com/item=3317/a-talking-head
this item starts the quest
https://tbc.wowhead.com/quest=460/resting-in-pieces

This quest is Horde only. The NPCs are showing on alliance characters

**Comment by Nerillida** [comment]
> version 6.3.10
> Map showing
> https://tbc.wowhead.com/npc=1939/rot-hide-brute
> They drop (among others)
> https://tbc.wowhead.com/item=3317/a-talking-head
> this item starts the quest
> https://tbc.wowhead.com/quest=460/resting-in-pieces
> 
> This quest is Horde only. The NPCs are showing on alliance characters

**Comment by drejjmit** [comment]
https://github.com/Questie/Questie/commit/cf00644cce4f962a7cf2952a23b9906c4979443f
Fixed for v6.3.11. Doesn't show up for me on v6.3.11

![image](https://user-images.githubusercontent.com/15526476/118933294-52553880-b949-11eb-88c4-456761bf64c7.png)

**Comment by Nerillida** [comment]
v6.3.11

Still showing as wrong races

![Screen Shot 2021-05-20 at 08 02 21](https://user-images.githubusercontent.com/55858788/118934215-05219880-b942-11eb-8e64-d9056be2c77e.png)

**Comment by drejjmit** [comment]
Draenei and Blood Elves are swapped. That's just a display error. The data is correct.

**Comment by Nerillida** [comment]
Thanks.
