### ISSUE TITLE
Questie: [ERROR] Missing objective data for quest 379 2

### ISSUE THREAD

**Issue by Morons** [Questie/Questie#3187]
Questie: [ERROR] Missing objective data for quest 379 2
 Just appeared after DBM update 
 Questie, v6.6.2
 no questy UI displaying, if you progress a ques it alone shows, but does not show copmplete
DBMCore, v25ee601

**Comment by Morons** [comment]
I fixed this by Reverting back to DBM-2.5.15-1b8cddc0-bcc

**Comment by Laumesis** [comment]
This is a real bug in our quest data.

Questid 379 on BBC has 2nd objective to explore some area. https://tbc.wowhead.com/quest=379/slake-that-thirst

Classic version has only 1 objective, same as in BCC, collecting items. https://classic.wowhead.com/quest=379/slake-that-thirst

Questie DB is missing 2nd objective on BBC and The error is outputed when Questie tries to send an addon comms message related to the quest.

I have no idea how to add an exploration object to questie in Questie DB. And not even sure what the area needed to explore is. TBC.Wowhead comments mention the quest was bugged but also mention fixed with date earlier than this bug report, so I guess the 2nd objective still exists in the game.

**Comment by BreakBB** [comment]
Looks like Blizzard kind of fixed this quest. The API for this quest is still broken though:

![grafik](https://user-images.githubusercontent.com/33514570/139699250-6dd385e6-8164-4305-8973-b1a1a4521a43.png)

But with just the five Water Pouches, you can hand in the quest.
