### ISSUE TITLE
Two error messages when launching in classic

### ISSUE THREAD

**Issue by ahos21** [Questie/Questie#4671]
I can't see any quest tracking on either the minimap or big map. I updated all the Curseforge addons, and disabled everything except Questie and still am having problems. I'm also getting two error messages:
Questie: [ERROR] Game Cache has still a broken quest log. Good quest: 1/0. Please report this on Github or Discord!
Questie: [ERROR] Error in thread...ce/AddOns/Questie/Modules/Options/QuestieOptions.lua:46: attempt to call method 'SetMinResize' (a nil value)

Haven't been able to figure it out!

**Comment by MyTechnoHunter** [comment]
please make sure you are running the newest version of questie
the SetMinResize has been fixed and the fact you are seeing that implies you are not up to date..

make sure with curseforge you update the right game client (the game you are running) you can also try right clicking the addon in curseforge and deleting save variables

**Comment by ahos21** [comment]
> 
all the addons are up to date! ive refreshed with /reload several times, restarted the game, restarted my PC...still getting the error code. it's the right game client (wotlk classic). also tried deleted save variables, still getting the error codes.

**Comment by MyTechnoHunter** [comment]
i absolutely PROMISE YOU you are not up to date! period

![image](https://user-images.githubusercontent.com/55214545/221730430-948da989-7573-42b9-958c-94d4da673a58.png)

THAT is the line in question in the wrath client.. in the file mentioned in your error in the first post of this issue..

PLEASE remove your questie folder... get the curseforge client or the wowup client or whichever client.. MAKE SURE its on the wrath version of the game, not retail/dragonflight/vanilla and search for and install questie

the literal only thing i can think of is that your game folder (and the interface\addons folder) is not where you think it is..
